<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="videojuegos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="videojuego" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string"/>
                            <xs:element name="estudio" type="xs:string"/>
                            <xs:element name="lanzamiento" type="xs:integer"/>
                            <xs:element name="genero" type="xs:string"/>
                            <xs:element name="plataforma" type="xs:string"/>
                            <xs:element name="precio" type="xs:decimal"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>